/* The following code was generated by JFlex 1.4.3 on 5/20/14 9:40 PM */

import java.lang.System;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 5/20/14 9:40 PM from the specification file
 * <tt>TolkLexer.lex</tt>
 */
class TolkLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\12\0\1\45\27\0\1\44\11\0\1\37\1\0\1\31\22\0\1\43"+
    "\1\13\1\0\1\26\1\35\1\0\1\24\1\1\3\0\1\14\1\0"+
    "\1\21\1\0\1\7\1\33\1\0\1\27\1\25\2\0\1\41\11\0"+
    "\1\2\1\15\1\42\1\32\1\5\1\0\1\12\1\40\1\34\1\0"+
    "\1\4\1\6\1\23\1\16\1\11\1\20\1\33\1\10\1\3\1\17"+
    "\1\22\1\0\1\41\1\36\1\30\uff86\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\16\1\1\2\1\1\1\3\3\1\14\0\1\4"+
    "\4\0\1\5\1\6\7\0\1\7\1\10\5\0\1\11"+
    "\5\0\1\12\6\0\1\13\3\0\1\14\4\0\1\15"+
    "\2\0\1\16\3\0\1\17\1\20\2\0\1\21\3\0"+
    "\1\22\1\23\1\0\1\24\1\25\1\26\3\0\1\27"+
    "\1\30\3\0\1\31\1\5";

  private static int [] zzUnpackAction() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\46\0\114\0\162\0\230\0\276\0\344\0\u010a"+
    "\0\u0130\0\u0156\0\u017c\0\u01a2\0\u01c8\0\u01ee\0\u0214\0\46"+
    "\0\u023a\0\46\0\u0260\0\u0286\0\u02ac\0\u02d2\0\u02f8\0\u031e"+
    "\0\u0344\0\u036a\0\u0390\0\u03b6\0\u03dc\0\u0402\0\u0428\0\u044e"+
    "\0\u0474\0\u049a\0\u04c0\0\u04e6\0\u050c\0\u0532\0\u0558\0\46"+
    "\0\u057e\0\u0558\0\u05a4\0\u05ca\0\u05f0\0\u0616\0\u063c\0\46"+
    "\0\46\0\u0662\0\u0688\0\u06ae\0\u06d4\0\u06fa\0\46\0\u0720"+
    "\0\u0746\0\u076c\0\u0792\0\u07b8\0\46\0\u07de\0\u0804\0\u082a"+
    "\0\u0850\0\u0876\0\u089c\0\u05f0\0\u08c2\0\u08e8\0\u090e\0\46"+
    "\0\u0934\0\u095a\0\u0980\0\u09a6\0\46\0\u09cc\0\u09f2\0\46"+
    "\0\u0a18\0\u0a3e\0\u0a64\0\46\0\46\0\u0a8a\0\u0ab0\0\46"+
    "\0\u0ad6\0\u0afc\0\u0b22\0\46\0\46\0\u0b48\0\46\0\46"+
    "\0\46\0\u0b6e\0\u0b94\0\u0bba\0\46\0\46\0\u0be0\0\u0c06"+
    "\0\u0c2c\0\46\0\46";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\2\1\6\1\7\1\10"+
    "\2\2\1\11\1\12\1\7\1\12\1\13\1\14\1\10"+
    "\1\15\2\2\1\11\1\16\1\17\1\5\1\2\1\20"+
    "\1\17\1\21\1\2\1\6\1\2\1\22\1\3\1\23"+
    "\1\2\1\24\1\25\51\0\1\26\46\0\1\27\12\0"+
    "\1\30\31\0\1\31\6\0\1\32\36\0\1\33\33\0"+
    "\1\34\11\0\1\35\2\0\1\36\45\0\1\37\2\0"+
    "\1\40\45\0\1\41\1\42\45\0\1\43\16\0\1\44"+
    "\26\0\1\45\10\0\1\46\25\0\1\47\6\0\1\50"+
    "\45\0\1\51\10\0\1\46\25\0\1\52\6\0\1\50"+
    "\44\0\1\53\57\0\1\34\30\0\1\54\43\0\1\27"+
    "\42\0\45\55\4\0\1\56\45\0\1\57\74\0\1\60"+
    "\43\0\1\61\37\0\1\62\26\0\1\63\76\0\1\64"+
    "\26\0\1\65\72\0\1\66\21\0\1\67\40\0\1\70"+
    "\36\0\1\71\2\0\1\72\51\0\1\73\45\0\1\74"+
    "\41\0\1\75\50\0\1\76\6\0\1\77\51\0\1\100"+
    "\26\0\1\101\51\0\1\76\46\0\1\102\37\0\1\103"+
    "\42\0\44\55\1\104\5\0\1\105\75\0\1\106\30\0"+
    "\1\107\45\0\1\110\45\0\1\75\44\0\1\111\46\0"+
    "\1\112\34\0\1\113\3\0\1\114\50\0\1\115\35\0"+
    "\1\116\72\0\1\117\17\0\1\120\60\0\1\121\33\0"+
    "\1\122\63\0\1\123\27\0\1\115\60\0\1\124\44\0"+
    "\1\125\33\0\1\126\43\0\1\127\102\0\1\130\16\0"+
    "\1\131\56\0\1\132\34\0\1\133\54\0\1\134\44\0"+
    "\1\135\41\0\1\136\1\0\1\136\70\0\1\137\10\0"+
    "\1\140\47\0\1\141\46\0\1\142\56\0\1\143\45\0"+
    "\1\77\36\0\1\144\47\0\1\145\63\0\1\44\23\0"+
    "\1\146\41\0\1\147\50\0\1\150\56\0\1\151\37\0"+
    "\1\152\54\0\1\153\26\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3154];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\15\1\1\11\1\1\1\11\3\1\14\0"+
    "\1\1\4\0\1\1\1\11\7\0\2\11\5\0\1\11"+
    "\5\0\1\11\6\0\1\1\3\0\1\11\4\0\1\11"+
    "\2\0\1\11\3\0\2\11\2\0\1\11\3\0\2\11"+
    "\1\0\3\11\3\0\2\11\3\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  TolkLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  TolkLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 112) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 24: 
          { return (new Symbol(sym.HASKELL));
          }
        case 26: break;
        case 10: 
          { return new Symbol(sym.BYEBYE);
          }
        case 27: break;
        case 14: 
          { return (new Symbol(sym.BOOK));
          }
        case 28: break;
        case 3: 
          { return new Symbol(sym.COMMA);
          }
        case 29: break;
        case 9: 
          { return (new Symbol(sym.PEN));
          }
        case 30: break;
        case 17: 
          { return new Symbol(sym.DIRECTION, Direction.SOUTH);
          }
        case 31: break;
        case 8: 
          { return new Symbol(sym.SAY);
          }
        case 32: break;
        case 25: 
          { return new Symbol(sym.LECTURER);
          }
        case 33: break;
        case 12: 
          { return new Symbol(sym.DIRECTION, Direction.EAST);
          }
        case 34: break;
        case 7: 
          { return new Symbol(sym.AND);
          }
        case 35: break;
        case 18: 
          { return (new Symbol(sym.PROGP));
          }
        case 36: break;
        case 15: 
          { return new Symbol(sym.DROP);
          }
        case 37: break;
        case 23: 
          { return (new Symbol(sym.PROLOG));
          }
        case 38: break;
        case 16: 
          { return new Symbol(sym.DIRECTION, Direction.WEST);
          }
        case 39: break;
        case 19: 
          { return new Symbol(sym.GREET);
          }
        case 40: break;
        case 2: 
          { return new Symbol(sym.PERIOD);
          }
        case 41: break;
        case 11: 
          { return new Symbol(sym.SOME_STRING, yytext());
          }
        case 42: break;
        case 22: 
          { return (new Symbol(sym.NUMME));
          }
        case 43: break;
        case 20: 
          { return new Symbol(sym.DIRECTION, Direction.NORTH);
          }
        case 44: break;
        case 6: 
          { return new Symbol(sym.TILL);
          }
        case 45: break;
        case 13: 
          { return new Symbol(sym.TAKE);
          }
        case 46: break;
        case 21: 
          { return (new Symbol(sym.LABNOTES));
          }
        case 47: break;
        case 5: 
          { return new Symbol(sym.ASSISTANT);
          }
        case 48: break;
        case 1: 
          { 
          }
        case 49: break;
        case 4: 
          { return new Symbol(sym.GO);
          }
        case 50: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
