
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 13 21:41:20 CEST 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LECTURER = 13;
  public static final int NUMME = 11;
  public static final int SAY = 5;
  public static final int TILL = 14;
  public static final int PERIOD = 15;
  public static final int SOME_STRING = 18;
  public static final int PROLOG = 9;
  public static final int HASKELL = 8;
  public static final int GO = 2;
  public static final int TAKE = 3;
  public static final int EOF = 0;
  public static final int ASSISTANT = 12;
  public static final int DIRECTION = 16;
  public static final int DROP = 4;
  public static final int error = 1;
  public static final int PROGP = 10;
  public static final int LABNOTES = 7;
  public static final int BOOK = 6;
  public static final int BYEBYE = 17;
}

