
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 14 09:15:34 CEST 2014
//----------------------------------------------------

import java.util.List;
import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Wed May 14 09:15:34 CEST 2014
  */
public class Tolk extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Tolk() {super();}

  /** Constructor which sets the default scanner. */
  public Tolk(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Tolk(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\035\000\002\002\004\000\002\002\004\000\002\002" +
    "\006\000\002\004\003\000\002\004\004\000\002\004\005" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\003\003\000\002\003\003\000\002\003\003\000\002" +
    "\005\004\000\002\006\004\000\002\007\004\000\002\010" +
    "\006\000\002\011\004\000\002\014\003\000\002\014\003" +
    "\000\002\014\003\000\002\012\004\000\002\012\004\000" +
    "\002\012\003\000\002\013\004\000\002\013\004\000\002" +
    "\013\003\000\002\015\003\000\002\016\003\000\002\016" +
    "\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\056\000\016\004\021\005\005\006\006\007\013\010" +
    "\017\027\015\001\002\000\004\002\060\001\002\000\020" +
    "\011\041\012\040\013\043\014\046\015\045\016\052\017" +
    "\051\001\002\000\020\011\041\012\040\013\043\014\046" +
    "\015\045\016\052\017\051\001\002\000\010\022\ufffb\023" +
    "\ufffb\025\ufffb\001\002\000\010\022\ufff8\023\ufff8\025\ufff8" +
    "\001\002\000\010\022\ufffa\023\ufffa\025\ufffa\001\002\000" +
    "\010\022\ufff7\023\ufff7\025\ufff7\001\002\000\004\030\035" +
    "\001\002\000\010\022\ufff9\023\ufff9\025\ufff9\001\002\000" +
    "\010\022\ufff6\023\ufff6\025\ufff6\001\002\000\004\022\032" +
    "\001\002\000\006\020\027\021\030\001\002\000\010\022" +
    "\ufffe\023\023\025\024\001\002\000\004\026\022\001\002" +
    "\000\010\022\ufff3\023\ufff3\025\ufff3\001\002\000\020\004" +
    "\021\005\005\006\006\007\013\010\017\022\ufffd\027\015" +
    "\001\002\000\004\002\000\001\002\000\004\022\ufffc\001" +
    "\002\000\006\022\ufffe\023\023\001\002\000\010\022\uffe5" +
    "\023\uffe5\025\uffe5\001\002\000\010\022\uffe6\023\uffe6\025" +
    "\uffe6\001\002\000\010\022\ufff1\023\ufff1\025\ufff1\001\002" +
    "\000\016\004\021\005\005\006\006\007\013\010\017\027" +
    "\015\001\002\000\004\025\034\001\002\000\004\002\uffff" +
    "\001\002\000\004\024\036\001\002\000\006\020\027\021" +
    "\030\001\002\000\010\022\ufff2\023\ufff2\025\ufff2\001\002" +
    "\000\010\022\uffe8\023\uffe8\025\uffe8\001\002\000\010\022" +
    "\uffeb\023\uffeb\025\uffeb\001\002\000\010\022\ufff0\023\ufff0" +
    "\025\ufff0\001\002\000\004\011\056\001\002\000\010\022" +
    "\uffee\023\uffee\025\uffee\001\002\000\004\012\055\001\002" +
    "\000\004\011\054\001\002\000\010\022\ufff4\023\ufff4\025" +
    "\ufff4\001\002\000\010\022\uffef\023\uffef\025\uffef\001\002" +
    "\000\010\022\uffe7\023\uffe7\025\uffe7\001\002\000\004\012" +
    "\053\001\002\000\010\022\uffe9\023\uffe9\025\uffe9\001\002" +
    "\000\010\022\uffec\023\uffec\025\uffec\001\002\000\010\022" +
    "\uffea\023\uffea\025\uffea\001\002\000\010\022\uffed\023\uffed" +
    "\025\uffed\001\002\000\010\022\ufff5\023\ufff5\025\ufff5\001" +
    "\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\056\000\022\002\003\003\017\004\015\005\006\006" +
    "\010\007\013\010\007\011\011\001\001\000\002\001\001" +
    "\000\012\012\041\013\047\014\056\015\043\001\001\000" +
    "\012\012\041\013\047\014\046\015\043\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\016\030\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\020\003\025" +
    "\004\024\005\006\006\010\007\013\010\007\011\011\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\016\003\032\005\006\006\010\007\013\010\007\011\011" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\016\036\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Tolk$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Tolk$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Tolk$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Tolk$actions {
  private final Tolk parser;

  /** Constructor */
  CUP$Tolk$actions(Tolk parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Tolk$do_action(
    int                        CUP$Tolk$act_num,
    java_cup.runtime.lr_parser CUP$Tolk$parser,
    java.util.Stack            CUP$Tolk$stack,
    int                        CUP$Tolk$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Tolk$result;

      /* select the action based on the action number */
      switch (CUP$Tolk$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // person ::= ASSISTANT 
            {
              People RESULT =null;
		 RESULT = People.ASSISTANT; 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("person",12, ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // person ::= LECTURER 
            {
              People RESULT =null;
		 RESULT = People.LECTURER; 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("person",12, ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // pen ::= PEN 
            {
              Things RESULT =null;
		 RESULT = Things.PEN; 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("pen",11, ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // labnotes ::= LABNOTES 
            {
              Things RESULT =null;
		 RESULT = Things.UNKNOWNLABNOTES; 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("labnotes",9, ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // labnotes ::= NUMME LABNOTES 
            {
              Things RESULT =null;
		 RESULT = Things.NUMMELABNOTES; 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("labnotes",9, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // labnotes ::= PROGP LABNOTES 
            {
              Things RESULT =null;
		 RESULT = Things.PROGPLABNOTES; 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("labnotes",9, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // book ::= BOOK 
            {
              Things RESULT =null;
		 RESULT = Things.UNKNOWNBOOK; 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("book",8, ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // book ::= PROLOG BOOK 
            {
              Things RESULT =null;
		 RESULT = Things.PROLOGBOOK;  
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("book",8, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // book ::= HASKELL BOOK 
            {
              Things RESULT =null;
		 RESULT = Things.HASKELLBOOK; 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("book",8, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // thing ::= pen 
            {
              Things RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).right;
		Things p = (Things)((java_cup.runtime.Symbol) CUP$Tolk$stack.peek()).value;
		 RESULT = p; 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("thing",10, ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // thing ::= labnotes 
            {
              Things RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).right;
		Things n = (Things)((java_cup.runtime.Symbol) CUP$Tolk$stack.peek()).value;
		 RESULT = n; 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("thing",10, ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // thing ::= book 
            {
              Things RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).right;
		Things b = (Things)((java_cup.runtime.Symbol) CUP$Tolk$stack.peek()).value;
		 RESULT = b; 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("thing",10, ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // greet_instr ::= GREET person 
            {
              Command RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).right;
		People p = (People)((java_cup.runtime.Symbol) CUP$Tolk$stack.peek()).value;
		 RESULT = new GreetCommand(p); 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("greet_instr",7, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // talk_instr ::= SAY SOME_STRING TILL person 
            {
              Command RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-2)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-2)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).right;
		People p = (People)((java_cup.runtime.Symbol) CUP$Tolk$stack.peek()).value;
		 RESULT = new SayCommand(s, p); 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("talk_instr",6, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-3)), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // go_instr ::= GO DIRECTION 
            {
              Command RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).right;
		Direction d = (Direction)((java_cup.runtime.Symbol) CUP$Tolk$stack.peek()).value;
		 RESULT = new GoCommand(d); 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("go_instr",5, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // drop_instr ::= DROP thing 
            {
              Command RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).right;
		Things t = (Things)((java_cup.runtime.Symbol) CUP$Tolk$stack.peek()).value;
		 RESULT = new DropCommand(t); 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("drop_instr",4, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // take_instr ::= TAKE thing 
            {
              Command RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).right;
		Things t = (Things)((java_cup.runtime.Symbol) CUP$Tolk$stack.peek()).value;
		 RESULT = new TakeCommand(t); 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("take_instr",3, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // one_instruction ::= BYEBYE 
            {
              Command RESULT =null;
		 RESULT = new QuitCommand(); 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("one_instruction",1, ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // one_instruction ::= greet_instr 
            {
              Command RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).right;
		Command i = (Command)((java_cup.runtime.Symbol) CUP$Tolk$stack.peek()).value;
		 RESULT = i; 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("one_instruction",1, ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // one_instruction ::= talk_instr 
            {
              Command RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).right;
		Command i = (Command)((java_cup.runtime.Symbol) CUP$Tolk$stack.peek()).value;
		 RESULT = i; 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("one_instruction",1, ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // one_instruction ::= go_instr 
            {
              Command RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).right;
		Command i = (Command)((java_cup.runtime.Symbol) CUP$Tolk$stack.peek()).value;
		 RESULT = i; 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("one_instruction",1, ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // one_instruction ::= drop_instr 
            {
              Command RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).right;
		Command i = (Command)((java_cup.runtime.Symbol) CUP$Tolk$stack.peek()).value;
		 RESULT = i; 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("one_instruction",1, ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // one_instruction ::= take_instr 
            {
              Command RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).right;
		Command i = (Command)((java_cup.runtime.Symbol) CUP$Tolk$stack.peek()).value;
		 RESULT = i; 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("one_instruction",1, ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // comma_sequence ::= one_instruction COMMA comma_sequence 
            {
              List RESULT =null;
		int i1left = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-2)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-2)).right;
		Command i1 = (Command)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-2)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).right;
		List i2 = (List)((java_cup.runtime.Symbol) CUP$Tolk$stack.peek()).value;
		 RESULT=new java.util.ArrayList(); RESULT.add(0,i1); RESULT.addAll(i2); 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("comma_sequence",2, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-2)), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // comma_sequence ::= one_instruction COMMA 
            {
              List RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).right;
		Command i = (Command)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).value;
		 RESULT=new java.util.ArrayList(); RESULT.add(0,i); 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("comma_sequence",2, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // comma_sequence ::= one_instruction 
            {
              List RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()).right;
		Command i = (Command)((java_cup.runtime.Symbol) CUP$Tolk$stack.peek()).value;
		 RESULT=new java.util.ArrayList(); RESULT.add(0,i); 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("comma_sequence",2, ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // instruction ::= comma_sequence AND one_instruction PERIOD 
            {
              List RESULT =null;
		int i1left = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-3)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-3)).right;
		List i1 = (List)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-3)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).right;
		Command i2 = (Command)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).value;
		 RESULT=new java.util.ArrayList(); RESULT.addAll(i1); RESULT.add(i2); 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("instruction",0, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-3)), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // instruction ::= one_instruction PERIOD 
            {
              List RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).right;
		Command i = (Command)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).value;
		 RESULT=new java.util.ArrayList(); RESULT.add(0,i); 
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("instruction",0, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= instruction EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).right;
		List start_val = (List)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).value;
		RESULT = start_val;
              CUP$Tolk$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)), ((java_cup.runtime.Symbol)CUP$Tolk$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Tolk$parser.done_parsing();
          return CUP$Tolk$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

